name: CI

on:
  pull_request_target:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        run: |
          echo ${{ github.base_ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.event.pull_request.base.ref }}
